### ISSUE TITLE
Anomaly Score 가 높다고 모두 Anomaly 인지요??

### ISSUE THREAD

**Issue by edwardcho** [mulkong/f-AnoGAN_with_Pytorch#1]
안녕하세요.
페북 케라스 코리아에서.. 알려주신 사이트에 들어왔습니다. 
소스코드로 열심히..해 보고 있는데요..
Anomaly Score 가 높다고 그 이미지가 꼭 Abnormal 이미지라고는 단정지을 수 있을까요??

올려주신 코드에서 CIFAR_10_DCGAN_AE 소스를 보고 있는데요..
아래쪽에 테스트 예제 이미지를 봤습니다.

처음 이미지가 사람이 보기엔 자동차(car) 인 것으로 보이는데...
Anomaly Score 가 바로 아래 비행기보다 높네요...

입력 이미지에 대해서
Anomaly Score 만으로 Normal 인지 Abnormal 인지 판단이 가능한지요??
가능하다면 Anomaly Score 가 어느정도 이상이면 Abnormal 로 판단해도 될런지요??

도움 주셔서 감사합니다.

**Comment by mulkong** [comment]
신뢰도가 있는 anomaly score를 얻을려면 우선 깨끗하고 안정적으로 학습 된 GAN이 우선적으로 학습이 되어야 합니다. 하지만, 제가 예제로 올린 모델은 DCGAN으로 Cifar10을 깔끔하게 generation을 하지 못해서 신뢰가 안되는 부분이 발생되는거 같습니다.

그리고 각 데이터마다 anomaly score threshold 값이 다 다르다고 생각을 합니다. 그래서 직접 데이터에 맞는 threshold 값을 찾으셔야 합니다.
