### ISSUE TITLE
입력 이미지의 크기를 변경하고 싶은데..어떻게 해야 할까요??

### ISSUE THREAD

**Issue by edwardcho** [mulkong/f-AnoGAN_with_Pytorch#2]
안녕하세요..
또 질문 남깁니다.
여기의 소스로 테스트 해 보고 있는데요..
입력이미지의 크기를 변경해 보고 싶은데..
어떻게 해야 할런지요??

**Comment by mulkong** [comment]
입력 이미지 크기를 변경하시려면 간단하게 cv2.resize() 함수를 사용하시면 될 거 같습니다.

참고 링크 : https://docs.opencv.org/2.4/modules/imgproc/doc/geometric_transformations.html?highlight=resize#resize

**Comment by edwardcho** [comment]
그럼 입력 이미지의 크기를 강제로 28x28 로 변경하여야 하나요??
그냥 원본이미지 크기로는 training 할 수는 없을까요?? (예 : 256x256)

**Comment by mulkong** [comment]
이미지 크기에 맞게 layer를 늘려주거나 kernel size를 변경하거나 이러한 작업을 진행 해주셔야 합니다.

**Comment by edwardcho** [comment]
f_AnoGAN_MNIST(DCGAN_+_AE)_using_Tensorboard.ipynb 
여기 코드에 이미지 크기를 변경할 수 있도록 해 두셨더라고요..

저는 이미지 크기를 256 으로 하고.. training 하고 있는데.
hyper-parameter 는 다음과 같이 변경하였습니다.

    # Define hyper-parameter
    n_epochs = 1
    batch_size = 4
    lr = 0.0002
    ndf = 256 #28
    ngf = 256 #28
    latent_dim = 100
    img_size = 256 #28
    channels = 1
    n_critic = 5
    sample_interval = 400
    training_label = 0
    split_rate = 0.8
    lambda_gp = 10

DCGAN 은 training 되었는데..
AutoEncoder 에서..
for epoch in range(n_epochs):

     ...
    fake_imgs = G(z)
    ...
    loss_imgs = criterion(fake_imgs, real_imgs)   <<- 여기에서 오류가 나왔습니다.

확인을 해보니, real_imgs 는   torch.Size([4, 1, 256, 256]) 인데
fake_imgs 는 torch.Size([4, 1, 252, 252]) 이렇게 나옵니다.

뭐가 문제인지 모르겠네요..흐미..

**Comment by edwardcho** [comment]
어렵습니다..흐미..
제가  위 처럼..
# Define hyper-parameter
n_epochs = 1
batch_size = 4
lr = 0.0002
ndf = 256 #28
ngf = 256 #28
latent_dim = 100
img_size = 256 #28
channels = 1
n_critic = 5
sample_interval = 400
training_label = 0
split_rate = 0.8
lambda_gp = 10

이렇게 하고나서..
DCGAN  을 training 하였는데..
DCGAN training 도중

for epoch in range(n_epochs):
    for i , (imgs, _) in enuerate(train_dataloader):
        real_imgs = imgs.to)device)

        ...
        fake_imgs = G(z)

여기에서 real_imgs 의 shape 는 torch.size([4, 1, 256, 256]) 인데,
fake_imgs 의 shape 은 torch.size([4, 1, 28, 28]) 입니다..

무엇을 수정해줘야 할런지요??

**Comment by mulkong** [comment]
코드를 다 안봐서 잘은 모르겠지만, 말씀해주신 내용으로만 본다면 Generator model쪽 layer를 수정을 하셔야 할겁니다. 그리고 256x256 이미지를 이용해서 DCGAN으로 학습을 진행하면 제대로 학습이 안될 것 입니다.

따라서 DCGAN 말고 고해상도 이미지를 generation 해주는 GAN 모델을 적용해주셔서 학습을 진행해야 제대로 원하는 값을 얻으실 수 있으실 것 입니다.

**Comment by edwardcho** [comment]
넵....
f_AnoGAN_MNIST(AE).ipynb 여기 소스코드는...이미지 크기를 변경해서..테스트 할 수 있었는데...

f_AnoGAN_MNIST(DCGAN_+_AE)_using_Tensorboard.ipynb 는 이미지 크기를 변경하면..안되는 것 같습니다.

**Comment by mulkong** [comment]
아니면 고해상도를 생성할 수 있는 GAN을 직접 적용시켜보시는건 어떠실까요? 저도 천천히 올리길 할건데 미리 한번 해보시는 것도 좋은 방법인거 같습니다.

PGGAN paper : https://research.nvidia.com/sites/default/files/pubs/2017-10_Progressive-Growing-of/karras2018iclr-paper.pdf
블로그 정리 : https://sensibilityit.tistory.com/508
[PGGAN TF] : https://github.com/tkarras/progressive_growing_of_gans
[PGGAN torch] : https://github.com/nashory/pggan-pytorch

올려드린 링크 한번 보시고 참고하셔서 직접 해보시면 큰 도움이 되실거 같습니다.
